### ISSUE TITLE
"trying to index a number value"

### ISSUE THREAD

**Issue by yinghuixia** [Nanne/ClassModel#1]
line 85 of learnclassmodel.lua

The code passes the first outer loop (line 80)

In the second loop, I got this error after resetting the model when trying to call getParameters(). Does anyone know what the trouble is? Thanks in advance.

**Comment by Nanne** [comment]
If I understand correctly it does create a class model for the first class? Does this image look alright?

Could you instead of resetting the model try calling line 63 and 66 again, to start with a fresh model. Does it give you the same problem then?

**Comment by yinghuixia** [comment]
Not really, but I was able to solve the problem by writing a new getParameters() method in ClassModel. I suppose our torch versions are different. but it's really weird that I get the correct digit 0 class.

May I ask what the parenthesis means in  local output = cmodel:forward({}) in line 92?

Would ClassModel be compatible with CudaTensor? I saw you included CudaTensor in your input method but I am not sure when I should call the method.

**Comment by Nanne** [comment]
Great that you were able to solve it, can you share the getParameters() method you wrote? I wrote this for an older version of Torch, and I haven't really been using Torch in the meantime, so could be that some internals have changed.

The forward method requires some input, but the because the image we're generating is stored in the first layer and passed onward from there we can just call forward() with an empty tensor, as to avoid any errors.

It should work fine with CudaTensors, depending on the model you're trying to visualise of course.
